import type { Metadata } from "next";
import { DM_Mono, Host_Grotesk } from "next/font/google";
import "./globals.css";
import { SplashScreen, SplashScreenStyles } from "./components/SplashScreen";
import { UpdateChecker } from "./components/UpdateChecker";

const dmMono = DM_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  style: ["normal"],
});

const hostGrotesk = Host_Grotesk({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <SplashScreenStyles />
      </head>
      <body className={`${hostGrotesk.variable} ${dmMono.variable} bg-background antialiased font-sans overflow-x-hidden`}>
        <SplashScreen />
        <UpdateChecker />
        {children}
      </body>
    </html>
  );
}
