/**
 * ============================================================================
 * GEMINI AI INTEGRATION MODULE
 * ============================================================================
 * 
 * PURPOSE: Integrate Google Gemini AI for screen recording timeline analysis
 * 
 * SUBMODULES:
 * - types: Data structures for timeline analysis
 * - embedded_key: Build-time embedded API key (generated by build.rs)
 * - prompt: Timeline analysis prompt builder
 * - client: Gemini API client for video analysis
 * - queue: Async job processing with retry logic
 * - formatter: Convert timeline to InfluxDB line protocol
 * 
 * FLOW:
 * 1. Recording segment completes -> job queued
 * 2. Queue processor uploads video to Gemini
 * 3. Gemini returns timeline JSON
 * 4. Timeline converted to line protocol
 * 5. Events sent to collector
 * 
 * API KEY PRIORITY:
 * 1. GEMINI_API_KEY environment variable (runtime override)
 * 2. Embedded key from build time (default)
 * 
 * ============================================================================
 */

pub mod types;
pub mod embedded_key;
pub mod prompt;
pub mod client;
pub mod queue;
pub mod formatter;

// Re-export commonly used types
pub use types::{TimelineEntry, TimelineAnalysis, GeminiJob, GeminiJobStatus, GeminiConfig};
pub use queue::{submit_job, init_queue, shutdown_queue, get_queue_status, QueueStatus};

// =============================================================================
// API Key Functions
// =============================================================================

/**
 * Get the Gemini API key
 * 
 * # Priority
 * 1. User-provided key from secure storage (settings)
 * 2. GEMINI_API_KEY environment variable (for runtime override/testing)
 * 3. Embedded key from build time (backwards compatibility)
 * 
 * # Returns
 * * `Ok(String)` - The API key
 * * `Err(String)` - Error message if no key available
 */
pub fn get_api_key() -> Result<String, String> {
    // Check for user-provided key from secure storage (requires AppHandle)
    // This is handled by get_api_key_with_app() which should be called when AppHandle is available
    
    // Check for runtime environment variable override
    if let Ok(key) = std::env::var("GEMINI_API_KEY") {
        if !key.is_empty() {
            log::debug!("Using Gemini API key from environment variable");
            return Ok(key);
        }
    }
    
    // Fall back to embedded key
    log::debug!("Using embedded Gemini API key");
    embedded_key::get_embedded_key()
}

/**
 * Get the Gemini API key with AppHandle (checks user-provided key first)
 * 
 * # Priority
 * 1. User-provided key from secure storage (settings)
 * 2. GEMINI_API_KEY environment variable (for runtime override/testing)
 * 3. Embedded key from build time (backwards compatibility)
 * 
 * # Returns
 * * `Ok(String)` - The API key
 * * `Err(String)` - Error message if no key available
 */
pub fn get_api_key_with_app(app: &tauri::AppHandle) -> Result<String, String> {
    // Check for user-provided key from secure storage first
    if let Ok(Some(key)) = crate::recording::config::load_gemini_api_key(app) {
        if !key.is_empty() {
            log::debug!("Using Gemini API key from user settings");
            return Ok(key);
        }
    }
    
    // Fall back to standard get_api_key() which checks env var and embedded key
    get_api_key()
}

/**
 * Check if API key is available (either env or embedded)
 * 
 * # Returns
 * * `true` if an API key is available
 * * `false` if no API key is configured
 */
pub fn has_api_key() -> bool {
    // Check environment variable first
    if let Ok(key) = std::env::var("GEMINI_API_KEY") {
        if !key.is_empty() {
            return true;
        }
    }
    // Fall back to checking embedded key
    embedded_key::has_embedded_key()
}

/**
 * Check if API key is available with AppHandle (checks user-provided key first)
 * 
 * # Returns
 * * `true` if an API key is available
 * * `false` if no API key is configured
 */
pub fn has_api_key_with_app(app: &tauri::AppHandle) -> bool {
    // Check for user-provided key from secure storage first
    if let Ok(Some(key)) = crate::recording::config::load_gemini_api_key(app) {
        if !key.is_empty() {
            return true;
        }
    }
    
    // Fall back to standard has_api_key() which checks env var and embedded key
    has_api_key()
}
